# Generated by Django 4.2.28 on 2026-03-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_SHIPPED', 'Order Shipped'), ('REFUND_PROCESSED', 'Refund Processed'), ('NEW_SUBORDER', 'New SubOrder'), ('PAYOUT_APPROVED', 'Payout Approved'), ('PAYOUT_REQUESTED', 'Payout Requested'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_REPLY_RECEIVED', 'Ticket Reply Received'), ('DISPUTE_ESCALATED', 'Dispute Escalated'), ('PROMOTION', 'Promotion')], max_length=50),
        ),
    ]
