# Generated by Django 4.2.28 on 2026-03-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_SHIPPED', 'Order Shipped'), ('REFUND_PROCESSED', 'Refund Processed'), ('NEW_SUBORDER', 'New SubOrder'), ('PAYOUT_APPROVED', 'Payout Approved'), ('PAYOUT_REQUESTED', 'Payout Requested'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_REPLY_RECEIVED', 'Ticket Reply Received'), ('DISPUTE_ESCALATED', 'Dispute Escalated'), ('PROMOTION', 'Promotion'), ('CB_ORDER_QUOTED', 'CB Order Quoted'), ('CB_ORDER_SHIPPED', 'CB Order Shipped Internationally'), ('CB_ORDER_DELIVERED', 'CB Order Delivered'), ('CB_CUSTOMS_HELD', 'CB Order Held at Customs')], max_length=50),
        ),
    ]
