"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    """
    Minimal .env loader (no external dependency).
    - Only sets keys that are not already present in the environment.
    - Ignores comments/blank lines.
    """
    try:
        if not path.exists():
            return
        for raw_line in path.read_text().splitlines():
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip().strip("'").strip('"')
            if key and key not in os.environ:
                os.environ[key] = value
    except Exception:
        return


# Load backend/.env for local development (ignored by git).
_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

DJANGO_ENV = os.getenv('DJANGO_ENV', 'development').lower()

def _env_bool(key: str, default: bool = False) -> bool:
    raw = os.getenv(key)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'y', 'on')

def _env_list(key: str) -> list[str]:
    raw = os.getenv(key, '')
    return [part.strip() for part in raw.split(',') if part.strip()]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '') or 'django-insecure-rktzfzviu=dz9(@@)x4_hvje#m*rjh2n+1dc28f*3mbw$5h=r5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', default=(DJANGO_ENV != 'production'))
if DJANGO_ENV == 'production' and SECRET_KEY.startswith('django-insecure-'):
    raise RuntimeError('DJANGO_SECRET_KEY must be set to a strong value in production.')

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver', '10.0.2.2'] if DEBUG else []

# CORS (dev defaults to permissive; lock down for production)
CORS_ALLOW_ALL_ORIGINS = _env_bool('CORS_ALLOW_ALL_ORIGINS', default=DEBUG)
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS')

CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS')

if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', default=True)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '3600'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
    SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', default=False)

    # If running behind a reverse proxy (e.g., Nginx), forward proto so Django knows the request is HTTPS.
    if _env_bool('USE_X_FORWARDED_PROTO', default=True):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'unfold',                       # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'users',
    'vendors',
    'reviews',
    'products',
    'orders',
    'coupons',
    'returns',
    'promotions',
    'notifications',
    'support',
    'logistics',
    'analytics',
    'discovery',
    'ads',
    'crossborder',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
if DATABASE_URL:
    parsed = urlparse(DATABASE_URL)
    if parsed.scheme in ('postgres', 'postgresql'):
        engine = 'django.db.backends.postgresql'
    elif parsed.scheme in ('sqlite', 'sqlite3'):
        engine = 'django.db.backends.sqlite3'
    else:
        raise RuntimeError(f'Unsupported DATABASE_URL scheme: {parsed.scheme}')

    query = parse_qs(parsed.query)
    DATABASES = {
        'default': {
            'ENGINE': engine,
            'NAME': (parsed.path or '').lstrip('/') if engine != 'django.db.backends.sqlite3' else (parsed.path or ''),
            'USER': parsed.username or '',
            'PASSWORD': parsed.password or '',
            'HOST': parsed.hostname or '',
            'PORT': str(parsed.port or ''),
            'OPTIONS': {k: v[0] for k, v in query.items()},
        }
    }
    if engine == 'django.db.backends.sqlite3':
        # Support sqlite:////absolute/path or sqlite:///relative/path
        path = parsed.path or ''
        if path.startswith('/'):
            DATABASES['default']['NAME'] = path
        else:
            DATABASES['default']['NAME'] = str(BASE_DIR / (path or 'db.sqlite3'))
        DATABASES['default'].pop('USER', None)
        DATABASES['default'].pop('PASSWORD', None)
        DATABASES['default'].pop('HOST', None)
        DATABASES['default'].pop('PORT', None)
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CACHE ---
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Rest Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Media files (Images uploads for products/categories)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Returns / RMA configuration
RMA_VENDOR_RESPONSE_HOURS = 48
RMA_DEFAULT_RETURN_WINDOW_DAYS = 7

# SSLCommerz Configuration
# NOTE: Set these via environment variables in production.
SSLCOMMERZ_STORE_ID = os.getenv('SSLCOMMERZ_STORE_ID', 'testbox')
SSLCOMMERZ_STORE_PASS = os.getenv('SSLCOMMERZ_STORE_PASS', 'qwerty')
SSLCOMMERZ_IS_SANDBOX = os.getenv('SSLCOMMERZ_IS_SANDBOX', 'true').lower() in (
    '1',
    'true',
    'yes',
    'y',
)

# Firebase Cloud Messaging (FCM)
# - Legacy: set FCM_MODE=legacy + FCM_SERVER_KEY
# - HTTP v1: set FCM_MODE=v1 + FCM_PROJECT_ID + (FCM_SERVICE_ACCOUNT_JSON or FCM_SERVICE_ACCOUNT_FILE)
FCM_MODE = os.getenv('FCM_MODE', 'v1').lower()
FCM_SERVER_KEY = os.getenv('FCM_SERVER_KEY', '')
FCM_PROJECT_ID = os.getenv('FCM_PROJECT_ID', '')
FCM_SERVICE_ACCOUNT_JSON = os.getenv('FCM_SERVICE_ACCOUNT_JSON', '')
FCM_SERVICE_ACCOUNT_FILE = os.getenv('FCM_SERVICE_ACCOUNT_FILE', '')

# Analytics / Personalization
def _clamp_int(value: str, default: int, min_value: int, max_value: int) -> int:
    try:
        parsed = int(str(value).strip())
    except Exception:
        return default
    return max(min_value, min(max_value, parsed))

ANALYTICS_RETENTION_DAYS = _clamp_int(
    os.getenv('ANALYTICS_RETENTION_DAYS', '90'),
    default=90,
    min_value=30,
    max_value=90,
)

# Celery Configuration Options
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat (periodic tasks)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Runs daily shortly after midnight UTC
    'vendors.compute_daily_vendor_metrics': {
        'task': 'vendors.tasks.compute_daily_vendor_metrics',
        'schedule': crontab(hour=0, minute=5),
    },
    # Releases due settlements (Delivery + 7 days) into available balance
    'vendors.release_due_settlements': {
        'task': 'vendors.tasks.release_due_settlements',
        'schedule': crontab(hour=0, minute=10),
    },
    # Poll SSLCommerz refunds to finalize original-method refunds (no webhook available in this integration).
    'returns.poll_sslcommerz_refunds': {
        'task': 'returns.tasks.poll_sslcommerz_refund_status',
        'schedule': crontab(minute='*/5'),
    },
    # Flags overdue support tickets (24h first response, 72h resolution)
    'support.flag_overdue_tickets': {
        'task': 'support.tasks.flag_overdue_tickets',
        'schedule': crontab(hour=0, minute=20),
    },
    # Poll couriers for tracking updates (fallback when webhooks are missing/unreliable).
    'logistics.poll_courier_updates': {
        'task': 'logistics.tasks.poll_courier_updates_task',
        'schedule': crontab(minute='*/30'),
    },
    # Purge raw behavioral events after retention window (privacy).
    'analytics.purge_old_user_events': {
        'task': 'analytics.tasks.purge_old_user_events',
        'schedule': crontab(hour=0, minute=30, day_of_week='sun'),
    },
    # Batch update product co-occurrence affinities.
    'discovery.compute_product_affinities': {
        'task': 'discovery.tasks.compute_product_affinities',
        'schedule': crontab(hour=1, minute=0),
    },
}


# ---------------------------------------------------------------------------
# Django Unfold – Admin UI Modernization
# ---------------------------------------------------------------------------
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def _unfold_environment(request):
    """Environment badge in the admin top-right corner."""
    env = DJANGO_ENV
    mapping = {
        'production': ['Production', 'danger'],
        'staging': ['Staging', 'warning'],
    }
    return mapping.get(env, ['Development', 'info'])


def _unfold_badge_orders_today(request):
    try:
        from orders.models import Order
        from django.utils import timezone
        return Order.objects.filter(
            created_at__date=timezone.now().date()
        ).count() or None
    except Exception:
        return None


def _unfold_badge_open_tickets(request):
    try:
        from support.models import Ticket
        return Ticket.objects.filter(
            status__in=['OPEN', 'IN_PROGRESS']
        ).count() or None
    except Exception:
        return None


def _unfold_badge_pending_payouts(request):
    try:
        from vendors.models import PayoutRequest
        return PayoutRequest.objects.filter(
            status='PENDING'
        ).count() or None
    except Exception:
        return None


def _unfold_badge_cb_in_transit(request):
    try:
        from crossborder.models import CrossBorderOrderRequest
        return CrossBorderOrderRequest.objects.filter(
            status__in=['ORDERED', 'SHIPPED_INTL']
        ).count() or None
    except Exception:
        return None


def _unfold_dashboard_callback(request, context):
    """Inject metrics into the admin index (dashboard) template."""
    from django.utils import timezone
    from datetime import timedelta
    from django.db.models import Sum, Count

    today = timezone.now().date()
    metrics = {}

    # Basic Metric Cards
    try:
        from orders.models import Order
        metrics['orders_today'] = Order.objects.filter(created_at__date=today).count()
        today_sales = Order.objects.filter(
            created_at__date=today,
            status__in=[Order.Status.PAID, Order.Status.SHIPPED, Order.Status.DELIVERED]
        ).aggregate(total=Sum('total_amount'))['total'] or 0
        metrics['sales_today'] = float(today_sales)
    except Exception:
        metrics['orders_today'] = 0
        metrics['sales_today'] = 0

    try:
        from vendors.models import PayoutRequest
        pending_payouts_agg = PayoutRequest.objects.filter(status='REQUESTED').aggregate(total=Sum('amount'))['total'] or 0
        metrics['pending_payout_amount'] = float(pending_payouts_agg)
    except Exception:
        metrics['pending_payout_amount'] = 0

    try:
        from support.models import Ticket
        metrics['open_tickets'] = Ticket.objects.filter(status__in=['OPEN', 'IN_PROGRESS']).count()
    except Exception:
        metrics['open_tickets'] = 0

    try:
        from crossborder.models import CrossBorderOrderRequest
        metrics['cb_in_transit'] = CrossBorderOrderRequest.objects.filter(
            status__in=['ORDERED', 'SHIPPED_INTL']
        ).count()
    except Exception:
        metrics['cb_in_transit'] = 0

    # Chart 1: Sales over the last 7 days (Line Chart)
    chart_sales_7d = {'labels': [], 'datasets': [{'label': 'Daily Sales (BDT)', 'data': [], 'backgroundColor': '#0ea5e9', 'borderColor': '#0ea5e9'}]}
    try:
        for i in range(6, -1, -1):
            d = today - timedelta(days=i)
            chart_sales_7d['labels'].append(d.strftime('%b %d'))
            day_total = Order.objects.filter(
                created_at__date=d,
                status__in=[Order.Status.PAID, Order.Status.SHIPPED, Order.Status.DELIVERED]
            ).aggregate(total=Sum('total_amount'))['total'] or 0
            chart_sales_7d['datasets'][0]['data'].append(float(day_total))
    except Exception:
        pass

    # Chart 2: Recent Order Statuses (Doughnut Chart)
    chart_order_status = {'labels': [], 'datasets': [{'data': [], 'backgroundColor': ['#eab308', '#3b82f6', '#22c55e', '#ef4444']}]}
    try:
        status_counts = Order.objects.filter(created_at__date__gte=today - timedelta(days=30)).values('status').annotate(count=Count('id'))
        status_map = {item['status']: item['count'] for item in status_counts}
        
        for status_code, bg_color in [('PENDING', '#eab308'), ('PAID', '#3b82f6'), ('DELIVERED', '#22c55e'), ('CANCELED', '#ef4444')]:
            chart_order_status['labels'].append(status_code)
            chart_order_status['datasets'][0]['data'].append(status_map.get(status_code, 0))
    except Exception:
        pass
    import json
    from django.utils.safestring import mark_safe

    # Formatted display values
    metrics['sales_today_display'] = f"৳{metrics.get('sales_today', 0):,.0f}"
    metrics['pending_payout_display'] = f"৳{metrics.get('pending_payout_amount', 0):,.0f}"

    context.update({
        'dashboard_metrics': metrics,
        'chart_sales_7d_json': mark_safe(json.dumps(chart_sales_7d)),
        'chart_order_status_json': mark_safe(json.dumps(chart_order_status)),
    })
    return context


# Permission helpers for sidebar visibility
def _perm_finance(request):
    u = request.user
    return u.is_superuser or u.groups.filter(name='Finance').exists()


def _perm_support(request):
    u = request.user
    return u.is_superuser or u.groups.filter(name='Support').exists()


def _perm_catalog(request):
    u = request.user
    return u.is_superuser or u.groups.filter(name='Catalog').exists()


def _perm_logistics(request):
    u = request.user
    return u.is_superuser or u.groups.filter(name='Logistics').exists()


UNFOLD = {
    'SITE_TITLE': 'Admin Console',
    'SITE_HEADER': 'Marketplace',
    'SITE_SUBHEADER': 'Operations Console',
    'SITE_URL': '/',
    'SITE_SYMBOL': 'storefront',
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': False,
    'SHOW_BACK_BUTTON': True,
    'ENVIRONMENT': 'config.settings._unfold_environment',
    'DASHBOARD_CALLBACK': 'config.settings._unfold_dashboard_callback',
    'BORDER_RADIUS': '6px',
    'COLORS': {
        'primary': {
            '50': '240 249 255',
            '100': '224 242 254',
            '200': '186 230 253',
            '300': '125 211 252',
            '400': '56 189 248',
            '500': '14 165 233',
            '600': '2 132 199',
            '700': '3 105 161',
            '800': '7 89 133',
            '900': '12 74 110',
            '950': '8 47 73',
        },
    },
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
        'navigation': [
            {
                'title': _('Dashboard'),
                'separator': True,
                'items': [
                    {
                        'title': _('Dashboard'),
                        'icon': 'dashboard',
                        'link': reverse_lazy('admin:index'),
                    },
                ],
            },
            {
                'title': _('E-Commerce Core'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Orders'),
                        'icon': 'shopping_cart',
                        'link': reverse_lazy('admin:orders_order_changelist'),
                        'badge': 'config.settings._unfold_badge_orders_today',
                        'badge_variant': 'info',
                    },
                    {
                        'title': _('Sub-Orders'),
                        'icon': 'local_shipping',
                        'link': reverse_lazy('admin:orders_suborder_changelist'),
                    },
                    {
                        'title': _('Products'),
                        'icon': 'inventory_2',
                        'link': reverse_lazy('admin:products_product_changelist'),
                    },
                    {
                        'title': _('Categories'),
                        'icon': 'category',
                        'link': reverse_lazy('admin:products_category_changelist'),
                    },
                    {
                        'title': _('Returns'),
                        'icon': 'assignment_return',
                        'link': reverse_lazy('admin:returns_returnrequest_changelist'),
                    },
                    {
                        'title': _('Refunds'),
                        'icon': 'payments',
                        'link': reverse_lazy('admin:returns_refund_changelist'),
                    },
                ],
            },
            {
                'title': _('Cross-Border Ops'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('CB Requests'),
                        'icon': 'public',
                        'link': reverse_lazy('admin:crossborder_crossborderorderrequest_changelist'),
                        'badge': 'config.settings._unfold_badge_cb_in_transit',
                        'badge_variant': 'warning',
                    },
                    {
                        'title': _('CB Products'),
                        'icon': 'flight',
                        'link': reverse_lazy('admin:crossborder_crossborderproduct_changelist'),
                    },
                    {
                        'title': _('CB Cost Config'),
                        'icon': 'tune',
                        'link': reverse_lazy('admin:crossborder_crossbordercostconfig_changelist'),
                    },
                ],
            },
            {
                'title': _('Users & Stores'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Customers'),
                        'icon': 'people',
                        'link': reverse_lazy('admin:users_user_changelist'),
                    },
                    {
                        'title': _('Vendors'),
                        'icon': 'store',
                        'link': reverse_lazy('admin:vendors_vendor_changelist'),
                    },
                ],
            },
            {
                'title': _('Finance'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Payout Requests'),
                        'icon': 'account_balance',
                        'link': reverse_lazy('admin:vendors_payoutrequest_changelist'),
                        'badge': 'config.settings._unfold_badge_pending_payouts',
                        'badge_variant': 'danger',
                    },
                    {
                        'title': _('Ledger'),
                        'icon': 'receipt_long',
                        'link': reverse_lazy('admin:vendors_ledgerentry_changelist'),
                        'permission': _perm_finance,
                    },
                    {
                        'title': _('Settlements'),
                        'icon': 'price_check',
                        'link': reverse_lazy('admin:vendors_settlementrecord_changelist'),
                        'permission': _perm_finance,
                    },
                    {
                        'title': _('Payout Methods'),
                        'icon': 'credit_card',
                        'link': reverse_lazy('admin:vendors_vendorpayoutmethod_changelist'),
                    },
                ],
            },
            {
                'title': _('Support'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Support Tickets'),
                        'icon': 'support_agent',
                        'link': reverse_lazy('admin:support_ticket_changelist'),
                        'badge': 'config.settings._unfold_badge_open_tickets',
                        'badge_variant': 'danger',
                    },
                    {
                        'title': _('Ticket Messages'),
                        'icon': 'chat',
                        'link': reverse_lazy('admin:support_ticketmessage_changelist'),
                    },
                ],
            },
            {
                'title': _('Growth & Marketing'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Coupons'),
                        'icon': 'confirmation_number',
                        'link': reverse_lazy('admin:coupons_coupon_changelist'),
                    },
                    {
                        'title': _('Banners'),
                        'icon': 'view_carousel',
                        'link': reverse_lazy('admin:promotions_banner_changelist'),
                    },
                    {
                        'title': _('Flash Sales'),
                        'icon': 'flash_on',
                        'link': reverse_lazy('admin:promotions_flashsale_changelist'),
                    },
                    {
                        'title': _('Collections'),
                        'icon': 'collections_bookmark',
                        'link': reverse_lazy('admin:discovery_collection_changelist'),
                    },
                    {
                        'title': _('Notifications'),
                        'icon': 'notifications',
                        'link': reverse_lazy('admin:notifications_notification_changelist'),
                    },
                ],
            },
            {
                'title': _('Logistics'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Couriers'),
                        'icon': 'bike_scooter',
                        'link': reverse_lazy('admin:logistics_courierintegration_changelist'),
                        'permission': _perm_logistics,
                    },
                    {
                        'title': _('Areas'),
                        'icon': 'map',
                        'link': reverse_lazy('admin:logistics_logisticsarea_changelist'),
                        'permission': _perm_logistics,
                    },
                    {
                        'title': _('Pickup Stores'),
                        'icon': 'warehouse',
                        'link': reverse_lazy('admin:logistics_logisticsstore_changelist'),
                        'permission': _perm_logistics,
                    },
                ],
            },
        ],
    },
}
