"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    """
    Minimal .env loader (no external dependency).
    - Only sets keys that are not already present in the environment.
    - Ignores comments/blank lines.
    """
    try:
        if not path.exists():
            return
        for raw_line in path.read_text().splitlines():
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip().strip("'").strip('"')
            if key and key not in os.environ:
                os.environ[key] = value
    except Exception:
        return


# Load backend/.env for local development (ignored by git).
_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rktzfzviu=dz9(@@)x4_hvje#m*rjh2n+1dc28f*3mbw$5h=r5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver', '10.0.2.2', '*']

CORS_ALLOW_ALL_ORIGINS = True  # For development only


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'users',
    'vendors',
    'reviews',
    'products',
    'orders',
    'coupons',
    'returns',
    'promotions',
    'notifications',
    'support',
    'logistics',
    'analytics',
    'discovery',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Rest Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Media files (Images uploads for products/categories)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Returns / RMA configuration
RMA_VENDOR_RESPONSE_HOURS = 48
RMA_DEFAULT_RETURN_WINDOW_DAYS = 7

# SSLCommerz Configuration
# NOTE: Set these via environment variables in production.
SSLCOMMERZ_STORE_ID = os.getenv('SSLCOMMERZ_STORE_ID', 'testbox')
SSLCOMMERZ_STORE_PASS = os.getenv('SSLCOMMERZ_STORE_PASS', 'qwerty')
SSLCOMMERZ_IS_SANDBOX = os.getenv('SSLCOMMERZ_IS_SANDBOX', 'true').lower() in (
    '1',
    'true',
    'yes',
    'y',
)

# Firebase Cloud Messaging (FCM)
# - Legacy: set FCM_MODE=legacy + FCM_SERVER_KEY
# - HTTP v1: set FCM_MODE=v1 + FCM_PROJECT_ID + (FCM_SERVICE_ACCOUNT_JSON or FCM_SERVICE_ACCOUNT_FILE)
FCM_MODE = os.getenv('FCM_MODE', 'v1').lower()
FCM_SERVER_KEY = os.getenv('FCM_SERVER_KEY', '')
FCM_PROJECT_ID = os.getenv('FCM_PROJECT_ID', '')
FCM_SERVICE_ACCOUNT_JSON = os.getenv('FCM_SERVICE_ACCOUNT_JSON', '')
FCM_SERVICE_ACCOUNT_FILE = os.getenv('FCM_SERVICE_ACCOUNT_FILE', '')

# Analytics / Personalization
def _clamp_int(value: str, default: int, min_value: int, max_value: int) -> int:
    try:
        parsed = int(str(value).strip())
    except Exception:
        return default
    return max(min_value, min(max_value, parsed))

ANALYTICS_RETENTION_DAYS = _clamp_int(
    os.getenv('ANALYTICS_RETENTION_DAYS', '90'),
    default=90,
    min_value=30,
    max_value=90,
)

# Celery Configuration Options
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat (periodic tasks)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Runs daily shortly after midnight UTC
    'vendors.compute_daily_vendor_metrics': {
        'task': 'vendors.tasks.compute_daily_vendor_metrics',
        'schedule': crontab(hour=0, minute=5),
    },
    # Releases due settlements (Delivery + 7 days) into available balance
    'vendors.release_due_settlements': {
        'task': 'vendors.tasks.release_due_settlements',
        'schedule': crontab(hour=0, minute=10),
    },
    # Poll SSLCommerz refunds to finalize original-method refunds (no webhook available in this integration).
    'returns.poll_sslcommerz_refunds': {
        'task': 'returns.tasks.poll_sslcommerz_refund_status',
        'schedule': crontab(minute='*/5'),
    },
    # Flags overdue support tickets (24h first response, 72h resolution)
    'support.flag_overdue_tickets': {
        'task': 'support.tasks.flag_overdue_tickets',
        'schedule': crontab(hour=0, minute=20),
    },
    # Poll couriers for tracking updates (fallback when webhooks are missing/unreliable).
    'logistics.poll_courier_updates': {
        'task': 'logistics.tasks.poll_courier_updates_task',
        'schedule': crontab(minute='*/30'),
    },
    # Purge raw behavioral events after retention window (privacy).
    'analytics.purge_old_user_events': {
        'task': 'analytics.tasks.purge_old_user_events',
        'schedule': crontab(hour=0, minute=30, day_of_week='sun'),
    },
    # Batch update product co-occurrence affinities.
    'discovery.compute_product_affinities': {
        'task': 'discovery.tasks.compute_product_affinities',
        'schedule': crontab(hour=1, minute=0),
    },
}
