# Generated by Django 4.2.28 on 2026-02-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_suborder_ship_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-generated UUID to prevent duplicate orders', max_length=64, null=True, unique=True),
        ),
    ]
