# Generated by Django 4.2.28 on 2026-02-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='System generated trxn_id for SSLCommerz', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='val_id',
            field=models.CharField(blank=True, help_text='Validation ID from SSLCommerz (needed for refunds)', max_length=255, null=True),
        ),
    ]
