# Generated by Django 4.2.28 on 2026-02-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_suborder_tracking_shipmentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentevent',
            name='external_event_id',
            field=models.CharField(blank=True, help_text='Idempotency key for courier webhooks', max_length=255, null=True, unique=True),
        ),
    ]
