# Generated by Django 4.2.28 on 2026-02-24 07:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('method', models.CharField(choices=[('ORIGINAL', 'Original Method'), ('WALLET', 'Wallet Credit')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('UNOPENED', 'Unopened'), ('OPENED', 'Opened'), ('USED', 'Used')], default='UNOPENED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('return_window_days', models.PositiveIntegerField(default=7)),
                ('sealed_return_window_days', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_return', models.BooleanField(default=True)),
                ('allow_replace', models.BooleanField(default=True)),
                ('sealed_requires_unopened', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('request_type', models.CharField(choices=[('RETURN', 'Return'), ('REPLACE', 'Replace')], max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VENDOR_APPROVED', 'Vendor Approved'), ('VENDOR_REJECTED', 'Vendor Rejected'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('DROPOFF_REQUESTED', 'Drop-off Requested'), ('RECEIVED', 'Received'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='SUBMITTED', max_length=30)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective'), ('WRONG_ITEM', 'Wrong Item'), ('NOT_AS_DESCRIBED', 'Not as described'), ('DAMAGED', 'Damaged in transit'), ('CHANGED_MIND', 'Changed my mind'), ('OTHER', 'Other')], max_length=30)),
                ('reason_details', models.TextField(blank=True)),
                ('fulfillment', models.CharField(choices=[('PICKUP', 'Pickup'), ('DROPOFF', 'Drop-off')], default='PICKUP', max_length=20)),
                ('pickup_window_start', models.DateTimeField(blank=True, null=True)),
                ('pickup_window_end', models.DateTimeField(blank=True, null=True)),
                ('dropoff_instructions', models.TextField(blank=True)),
                ('refund_method_preference', models.CharField(choices=[('ORIGINAL', 'Original Method'), ('WALLET', 'Wallet Credit')], default='ORIGINAL', max_length=20)),
                ('vendor_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_note', models.TextField(blank=True)),
                ('customer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
