# Generated by Django 4.2.28 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_sealed',
            field=models.BooleanField(default=False, help_text="Sealed items may have stricter return rules (e.g., must be unopened)."),
        ),
    ]

