# Generated by Django 4.2.28 on 2026-02-28 06:45

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_avg_rating_product_review_count'),
    ]

    operations = [
        TrigramExtension(),
    ]
