# Generated by Django 4.2.28 on 2026-02-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productoption_created_at_productoption_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Master on/off switch.')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority items appear first. Use 0–100.')),
                ('starts_at', models.DateTimeField(help_text='When this promotion becomes visible.')),
                ('ends_at', models.DateTimeField(help_text='When this promotion expires.')),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('NEW', 'New Users'), ('RETURNING', 'Returning Users'), ('VIP', 'VIP Users')], default='ALL', help_text='Which user segment should see this.', max_length=20)),
                ('platform', models.CharField(choices=[('ALL', 'All Platforms'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='ALL', help_text='Which platform should display this.', max_length=20)),
                ('locale', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', help_text='Language/locale targeting.', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Headline text overlay.', max_length=120)),
                ('subtitle', models.CharField(blank=True, help_text='Sub-headline text overlay.', max_length=200)),
                ('image', models.ImageField(help_text='Recommended: 1080×500px, JPEG/WebP, < 500KB.', upload_to='promotions/banners/')),
                ('link_type', models.CharField(choices=[('PRODUCT', 'Product Detail'), ('CATEGORY', 'Category Filter'), ('URL', 'External/Custom URL'), ('SEARCH', 'Search Query'), ('NONE', 'No Link')], default='NONE', help_text='What tapping the banner opens.', max_length=20)),
                ('link_value', models.CharField(blank=True, help_text='Product ID, Category Slug, URL, or Search query depending on link_type.', max_length=500)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-priority', 'starts_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Master on/off switch.')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority items appear first. Use 0–100.')),
                ('starts_at', models.DateTimeField(help_text='When this promotion becomes visible.')),
                ('ends_at', models.DateTimeField(help_text='When this promotion expires.')),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('NEW', 'New Users'), ('RETURNING', 'Returning Users'), ('VIP', 'VIP Users')], default='ALL', help_text='Which user segment should see this.', max_length=20)),
                ('platform', models.CharField(choices=[('ALL', 'All Platforms'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='ALL', help_text='Which platform should display this.', max_length=20)),
                ('locale', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', help_text='Language/locale targeting.', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="e.g., 'Mega Monday Flash Sale'", max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sales',
                'ordering': ['-priority', 'starts_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('PRICE', 'Fixed Price'), ('PERCENT', 'Percentage Off')], default='PRICE', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='If PRICE: the sale price. If PERCENT: the % off (e.g., 30 = 30% off).', max_digits=10)),
                ('purchase_limit_total', models.PositiveIntegerField(blank=True, help_text='Max total units for this deal across all users. Null = unlimited.', null=True)),
                ('max_per_user', models.PositiveIntegerField(blank=True, help_text='Max units a single user can buy at this price. Null = unlimited.', null=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order within the flash sale. Lower = first.')),
                ('is_active', models.BooleanField(default=True, help_text='Disable individual items within a sale.')),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='promotions.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_entries', to='products.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('flash_sale', 'product')},
            },
        ),
        migrations.AddField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='flash_sales', through='promotions.FlashSaleProduct', to='products.product'),
        ),
        migrations.CreateModel(
            name='FeaturedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Master on/off switch.')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority items appear first. Use 0–100.')),
                ('starts_at', models.DateTimeField(help_text='When this promotion becomes visible.')),
                ('ends_at', models.DateTimeField(help_text='When this promotion expires.')),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('NEW', 'New Users'), ('RETURNING', 'Returning Users'), ('VIP', 'VIP Users')], default='ALL', help_text='Which user segment should see this.', max_length=20)),
                ('platform', models.CharField(choices=[('ALL', 'All Platforms'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='ALL', help_text='Which platform should display this.', max_length=20)),
                ('locale', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', help_text='Language/locale targeting.', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Section heading shown to users.', max_length=120)),
                ('section_type', models.CharField(choices=[('TRENDING', 'Trending 🔥'), ('NEW_ARRIVALS', 'New Arrivals ✨'), ('TOP_RATED', 'Top Rated ⭐'), ('CURATED', 'Hand-Picked by Admin')], default='CURATED', max_length=20)),
                ('products', models.ManyToManyField(blank=True, help_text='For CURATED type: select products manually. For others, products are fetched dynamically.', related_name='featured_sections', to='products.product')),
            ],
            options={
                'verbose_name': 'Featured Section',
                'verbose_name_plural': 'Featured Sections',
                'ordering': ['-priority', 'starts_at'],
                'abstract': False,
            },
        ),
    ]
