# Generated by Django 4.2.28 on 2026-03-03 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('ADD_TO_CART', 'Add to cart'), ('PURCHASE', 'Purchase'), ('IMPRESSION', 'Impression')], max_length=30)),
                ('source', models.CharField(choices=[('HOME', 'Home'), ('SEARCH', 'Search'), ('PDP', 'Product detail'), ('COLLECTION', 'Collection'), ('NOTIFICATION', 'Notification'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('session_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'created_at'], name='ue_product_created_idx'), models.Index(fields=['session_id', 'created_at'], name='ue_session_created_idx'), models.Index(condition=models.Q(('user__isnull', False)), fields=['user', 'created_at'], name='ue_user_created_idx')],
            },
        ),
    ]
