# Generated by Django 4.2.28 on 2026-03-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
