# Generated by Django 4.2.28 on 2026-03-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='cms/banners/')),
                ('target_type', models.CharField(choices=[('NONE', 'None'), ('EXTERNAL_URL', 'External URL'), ('PRODUCT', 'Product'), ('CATEGORY', 'Category'), ('PAGE', 'Page')], default='NONE', max_length=20)),
                ('target_value', models.CharField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('ALL', 'All'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='ALL', max_length=20)),
                ('position', models.CharField(choices=[('HOME_TOP', 'Home Top'), ('HOME_MID', 'Home Mid')], default='HOME_TOP', max_length=20)),
            ],
            options={
                'ordering': ['position', 'display_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Orders', 'Orders'), ('Payments', 'Payments'), ('Shipping', 'Shipping'), ('Returns', 'Returns'), ('Account', 'Account')], max_length=30)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('page_type', models.CharField(choices=[('PRIVACY', 'Privacy Policy'), ('TERMS', 'Terms & Conditions'), ('ABOUT', 'About Us'), ('REFUND_POLICY', 'Refund Policy'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=30)),
                ('content', models.TextField(blank=True, default='')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/settings/')),
                ('setting_type', models.CharField(choices=[('TEXT', 'Text'), ('URL', 'URL'), ('BOOLEAN', 'Boolean'), ('IMAGE', 'Image'), ('JSON', 'JSON')], default='TEXT', max_length=20)),
                ('group', models.CharField(choices=[('branding', 'Branding'), ('contact', 'Contact'), ('social', 'Social'), ('app', 'App'), ('maintenance', 'Maintenance')], default='app', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
    ]
