upstream django {
    server unix:/run/gunicorn.sock;
}

server {
    listen 80;
    server_name shopease.chickenkiller.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /var/www/ecommerce/staticfiles/;
    }

    location /media/ {
        alias /var/www/ecommerce/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://django;
    }
}
