# Generated by Django 4.2.28 on 2026-02-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('PRODUCT_UPLOAD', 'Product Upload'), ('PRICE_UPDATE', 'Price Update'), ('STOCK_UPDATE', 'Stock Update')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL_SUCCESS', 'Partial Success')], default='PENDING', max_length=20)),
                ('file', models.FileField(upload_to='bulk_jobs/')),
                ('result_report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_jobs', to='vendors.vendor')),
            ],
        ),
    ]
