# Generated by Django 4.2.28 on 2026-02-25 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_bulkjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPerformanceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('shipped_count', models.PositiveIntegerField(default=0)),
                ('canceled_count', models.PositiveIntegerField(default=0)),
                ('late_shipments', models.PositiveIntegerField(default=0)),
                ('avg_handling_seconds', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('vendor', 'date')},
            },
        ),
    ]
