# Generated by Django 4.2.28 on 2026-02-26 08:31

from django.db import migrations, models
import django.db.models.deletion


def _backfill_vendor_buckets(apps, schema_editor):
    Vendor = apps.get_model('vendors', 'Vendor')
    for v in Vendor.objects.all():
        # Migrate legacy `balance` into the new AVAILABLE bucket by default.
        if (v.available_balance or 0) == 0 and (v.pending_balance or 0) == 0 and (v.held_balance or 0) == 0:
            v.available_balance = v.balance
        if (v.total_earned_lifetime or 0) == 0:
            v.total_earned_lifetime = v.balance
        v.save(update_fields=['available_balance', 'total_earned_lifetime'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_shipmentevent_external_event_id'),
        ('vendors', '0003_vendorperformancedaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='held_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_earned_lifetime',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_withdrawn_lifetime',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.CreateModel(
            name='VendorPayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('BANK', 'Bank'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], max_length=20)),
                ('label', models.CharField(blank=True, help_text="e.g. 'Main bank', 'bKash personal'", max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-is_verified', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RELEASED', 'Released')], default='PENDING', max_length=20)),
                ('settlement_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('sub_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_record', to='orders.suborder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_records', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('SALE_CREDIT_PENDING', 'Sale credit (Pending)'), ('SETTLEMENT_RELEASE', 'Settlement release'), ('PAYOUT_REQUEST_HOLD', 'Payout request hold'), ('PAYOUT_REJECTED_RELEASE', 'Payout rejected release'), ('PAYOUT_PAID', 'Payout paid')], max_length=50)),
                ('bucket', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('HELD', 'Held')], max_length=20)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('FAILED', 'Failed')], default='POSTED', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_type', models.CharField(choices=[('SUBORDER', 'SubOrder'), ('PAYOUT', 'Payout'), ('REFUND', 'Refund')], max_length=20)),
                ('reference_id', models.IntegerField()),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key', 'entry_type', 'bucket', 'direction'), name='vendors_ledger_idempotency_unique'),
        ),
        migrations.RunPython(_backfill_vendor_buckets, migrations.RunPython.noop),
    ]
