# Generated by Django 4.2.28 on 2026-02-28 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_available_balance_vendor_held_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/covers/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/logos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='policy_summary',
            field=models.TextField(blank=True, help_text='Summary of shipping/return policies'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
