# Generated by Django 4.2.28 on 2026-03-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_debt_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('SALE_CREDIT_PENDING', 'Sale credit (Pending)'), ('SETTLEMENT_RELEASE', 'Settlement release'), ('PAYOUT_REQUEST_HOLD', 'Payout request hold'), ('PAYOUT_REJECTED_RELEASE', 'Payout rejected release'), ('PAYOUT_PAID', 'Payout paid'), ('REFUND_DEBIT', 'Refund debit')], max_length=50),
        ),
    ]
