# Generated by Django 4.2.28 on 2026-03-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_ledgerentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='ad_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='bucket',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('HELD', 'Held'), ('AD_CREDITS', 'Ad Credits')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('SALE_CREDIT_PENDING', 'Sale credit (Pending)'), ('SETTLEMENT_RELEASE', 'Settlement release'), ('PAYOUT_REQUEST_HOLD', 'Payout request hold'), ('PAYOUT_REJECTED_RELEASE', 'Payout rejected release'), ('PAYOUT_PAID', 'Payout paid'), ('REFUND_DEBIT', 'Refund debit'), ('AD_CREDIT_TOPUP', 'Ad credit top-up'), ('AD_SPEND_CLICK', 'Ad spend (Click)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reference_type',
            field=models.CharField(choices=[('SUBORDER', 'SubOrder'), ('PAYOUT', 'Payout'), ('REFUND', 'Refund'), ('AD_CAMPAIGN', 'Ad Campaign')], max_length=20),
        ),
    ]
