# Generated by Django 4.2.28 on 2026-03-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_enable_pg_trgm'),
        ('vendors', '0008_vendor_ad_balance_alter_ledgerentry_bucket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductAnalyticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('carts', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sponsored_impressions', models.PositiveIntegerField(default=0)),
                ('sponsored_clicks', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_daily', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_analytics_daily', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-date', '-purchases'],
                'unique_together': {('vendor', 'product', 'date')},
            },
        ),
    ]
