# Generated by Django 4.2.28 on 2026-03-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendorproductanalyticsdaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Controls if vendor products are visible in search/discovery'),
        ),
        migrations.AlterField(
            model_name='bulkjob',
            name='job_type',
            field=models.CharField(choices=[('PRODUCT_UPLOAD', 'Product Upload'), ('PRICE_UPDATE', 'Price Update'), ('STOCK_UPDATE', 'Stock Update'), ('VARIANT_UPLOAD', 'Variant Upload'), ('SCHEDULED_PROMOTION', 'Scheduled Promotion')], max_length=50),
        ),
    ]
