# Generated by Django 4.2.28 on 2026-03-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_vendor_is_live_alter_bulkjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('SALE_CREDIT_PENDING', 'Sale credit (Pending)'), ('SETTLEMENT_RELEASE', 'Settlement release'), ('PAYOUT_REQUEST_HOLD', 'Payout request hold'), ('PAYOUT_REJECTED_RELEASE', 'Payout rejected release'), ('PAYOUT_PAID', 'Payout paid'), ('REFUND_DEBIT', 'Refund debit'), ('AD_CREDIT_TOPUP', 'Ad credit top-up'), ('AD_SPEND_CLICK', 'Ad spend (Click)'), ('CB_PAYMENT_RECEIVED', 'CB Payment Received'), ('CB_ITEM_COST', 'CB Real Item Purchase Cost'), ('CB_SERVICE_FEE', 'CB Service Fee Margin'), ('CB_TOPUP_RECEIVED', 'CB Top-up Received'), ('CB_REFUND', 'CB Refund')], max_length=50),
        ),
    ]
