# Generated by Django 4.2.28 on 2026-03-07 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courierintegration',
            new_name='logistics_c_courier_03d1b7_idx',
            old_name='logistics_courier_2da0ef_idx',
        ),
        migrations.RenameIndex(
            model_name='logisticsarea',
            new_name='logistics_l_courier_5a2fbd_idx',
            old_name='logistics_courier_1e2d7b_idx',
        ),
        migrations.RenameIndex(
            model_name='logisticsarea',
            new_name='logistics_l_courier_3564bd_idx',
            old_name='logistics_courier_8ed8a8_idx',
        ),
        migrations.RenameIndex(
            model_name='logisticsstore',
            new_name='logistics_l_courier_aa2b92_idx',
            old_name='logistics_courier_403bb4_idx',
        ),
    ]
