# Generated by Django 4.2.28 on 2026-03-03 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='collections/')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('targeting', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='discovery.collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='collections', through='discovery.CollectionItem', to='products.product'),
        ),
        migrations.CreateModel(
            name='ProductAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_from', to='products.product')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_to', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['from_product', '-score'], name='pa_from_score_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productaffinity',
            constraint=models.UniqueConstraint(fields=('from_product', 'to_product'), name='uniq_product_affinity_edge'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'sort_order'], name='colitem_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'product'), name='uniq_collection_product'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='col_active_window_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['-priority'], name='col_priority_idx'),
        ),
    ]
