# Generated by Django 4.2.28 on 2026-03-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossborder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossborderorderrequest',
            name='estimated_cost_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='{item_price_bdt, intl_shipping_bdt, service_fee_bdt, customs_est_bdt, total_bdt}'),
        ),
    ]
