# ═══════════════════════════════════════════════════════════════════
# VENDORS SERIALIZERS
# ═══════════════════════════════════════════════════════════════════
#
# CONCEPT: What is a Serializer?
# ──────────────────────────────
# Remember from users/serializers.py — a serializer is a TRANSLATOR.
# It converts between Python objects (Django models) ⟷ JSON (for the API).
#
# But serializers also do VALIDATION:
#   - Is store_name provided? Is it unique?
#   - Is the data in the correct format?
# Think of a serializer as a SECURITY GUARD at the entrance of your database.
# It checks every piece of data before letting it in.
#
# ═══════════════════════════════════════════════════════════════════

from rest_framework import serializers
from .models import Vendor


class VendorSerializer(serializers.ModelSerializer):
    """
    WHAT: Translates Vendor model ⟷ JSON
    WHEN USED:
      - Creating a new vendor (POST /api/vendors/onboarding/)
      - Viewing vendor profile (GET /api/vendors/me/)
    """

    class Meta:
        model = Vendor
        # These are the fields that will appear in the JSON response
        fields = ('id', 'store_name', 'description', 'is_approved', 'created_at')

        # read_only_fields = fields the API user CANNOT set.
        # Why? Because:
        #   - 'id' is auto-generated by the database
        #   - 'is_approved' should only be changed by an ADMIN, not the vendor themselves
        #   - 'created_at' is auto-set by Django (auto_now_add=True in the model)
        read_only_fields = ('id', 'is_approved', 'created_at')

    # ─── WHY NO create() override here? ─────────────────────────
    # Unlike UserRegistrationSerializer, we DON'T override create().
    # That's because the default ModelSerializer.create() works fine here.
    # We'll handle linking the vendor to the user in the VIEW, not the serializer.
    # Rule of thumb: Serializer = data validation. View = business logic.
