# Generated by Django 4.2.28 on 2026-03-04 06:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_enable_pg_trgm'),
        ('vendors', '0008_vendor_ad_balance_alter_ledgerentry_bucket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_per_click', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXHAUSTED', 'Exhausted')], default='DRAFT', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('is_sponsored_label_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='products.product')),
                ('target_categories', models.ManyToManyField(blank=True, related_name='targeted_ad_campaigns', to='products.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True)),
                ('source', models.CharField(max_length=50)),
                ('minute_bucket', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.adcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True)),
                ('click_id', models.UUIDField(help_text='Client-generated UUID for idempotency', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.adcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='adimpression',
            constraint=models.UniqueConstraint(fields=('campaign', 'session_id', 'source', 'minute_bucket'), name='unique_ad_impression_per_minute'),
        ),
    ]
