# Generated by Django 4.2.28 on 2026-03-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personalization_enabled',
            field=models.BooleanField(default=True, help_text='If false, the system will not log behavior events for personalization.'),
        ),
    ]
