[program:gunicorn]
directory=/home/ubuntu/ecommerce_app/backend
command=/home/ubuntu/ecommerce_app/backend/venv/bin/gunicorn \
    --access-logfile - \
    --workers 3 \
    --bind unix:/run/gunicorn.sock \
    config.wsgi:application

user=ubuntu
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn/gunicorn.err.log
stdout_logfile=/var/log/gunicorn/gunicorn.out.log

[program:celery-worker]
directory=/home/ubuntu/ecommerce_app/backend
command=/home/ubuntu/ecommerce_app/backend/venv/bin/celery -A config worker --loglevel=info
user=ubuntu
autostart=true
autorestart=true
stderr_logfile=/var/log/celery/worker.err.log
stdout_logfile=/var/log/celery/worker.out.log

[program:celery-beat]
directory=/home/ubuntu/ecommerce_app/backend
command=/home/ubuntu/ecommerce_app/backend/venv/bin/celery -A config beat --loglevel=info
user=ubuntu
autostart=true
autorestart=true
stderr_logfile=/var/log/celery/beat.err.log
stdout_logfile=/var/log/celery/beat.out.log
